### PR TITLE
ucsc pledge example

### PR DESCRIPTION
**Pull request by carlosmalt**

### CODE REVIEW

**Comment by carlosmalt** [comment]
This pull request
- list possible pledge items for UCSC 
- extends `figure.html` to include the `url:` attribute so that figures can link to websites
- adds ucsc logo and higher res ucsc ospo logo

**Comment by cranmer** [comment]
looks good. Need to check if there should be an if/then/else like logic for the url

**Comment by carlosmalt** [comment]
Thanks @cranmer, I've added that (tested on a local setup). 

Any chance you can netlify this repository? It's free and it creates a preview for every commit to a branch and inserts the link to the preview into the pull request. Very convenient for testing. Here is some documentation I found for jekyll sites: https://www.netlify.com/blog/2020/04/02/a-step-by-step-guide-jekyll-4.0-on-netlify/

**Comment by cranmer** [comment]
I created an issue for netlify. It's a good idea, will do when I have a chance.

**Pull request merged**
